#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Apr 10, 2019 03:14:07 PM IST  platform: Windows NT

import sys
import pymysql
import ADMINLIST
import admin_user_option
from tkinter import *
from tkinter import messagebox

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global ent1
    ent1 = tk.StringVar()
    global ent2
    ent2 = tk.StringVar()
    
def login():

    try:
        db=pymysql.connect("localhost","root","1234","test",3307)
        c=db.cursor()
        sql="select * from admins where id='%s' and password='%s'"%(ent1.get(),ent2.get())
        c.execute(sql)
        result=c.fetchall()
        counter=0
        id=0
        for x in result:
            counter=counter+1
            id=x[1]
        if counter>0:
            print("Login success")
            destroy_window()
            ADMINLIST.vp_start_gui()
            messagebox.showinfo('Login','USER VERIFIED')
            db.close()
        else:
            print("INVALID USER")
            #messagebox.showinfo('Login','INVALID USER')
            
                
    except:
        messagebox.showinfo('NO DATA','NO SUCH DATA AVAILABLE.....')


def back():
    destroy_window()
    admin_user_option.vp_start_gui()

    
def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import admin
    admin.vp_start_gui()




