#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Apr 10, 2019 03:14:16 PM IST  platform: Windows NT

import sys
from PIL import Image,ImageTk
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import admin_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    admin_support.set_Tk_var()
    top = Toplevel1 (root)
    admin_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    admin_support.set_Tk_var()
    top = Toplevel1 (w)
    admin_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Showcard Gothic} -size 20 -weight bold "  \
            #"-slant italic -underline 1 -overstrike 0"
        font11 = "-family {Segoe UI red} -size 15 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"


        top.geometry("1350x689-5+4")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.0, rely=0.0,relheight=1.500,relwidth=2.0, height=41, width=454)
        self.Canvas1.configure(selectbackground="#fca367")
        self.Canvas1.configure(selectforeground="#3617ff")
        self.Canvas1.configure(relief="raised")
        self.Canvas1.configure(width=864)
        self.Canvas1.configure(borderwidth="2")
        
        self.img = Image.open("bbk.jpg")
        self.tkimage = ImageTk.PhotoImage(self.img)
        resized = self.img.resize((1500, 750),Image.ANTIALIAS)
        self.imagee = ImageTk.PhotoImage(resized)

        self.Canvas1.create_image(0,0,image=self.imagee,anchor="nw")
        

        '''self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.042, rely=0.033, relheight=0.924
                , relwidth=0.915)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(background="cyan")
        self.Frame1.configure(width=549)'''

        '''self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.036, rely=0.048, height=49, width=175)
        self.Label1.configure(background="black")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="white")
        self.Label1.configure(text=#ADMIN ID)
        self.Label1.configure(width=84)'''

        self.Canvas1.create_text(250,50,text="Admin Email",fill="white",font=('bold',25))


        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.383, rely=0.072,height=38, relwidth=0.556)
        self.Entry1.configure(background="black")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font=font11)
        self.Entry1.configure(foreground="white")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(textvariable=admin_support.ent1)

        
        self.Canvas1.create_text(250,280,text="Password",fill="white",font=('bold',25))

        
        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.383, rely=0.380,height=38, relwidth=0.556)
        self.Entry2.configure(background="black")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font=font11)
        self.Entry2.configure(foreground="white")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(textvariable=admin_support.ent2)
        self.Entry2.configure(show="**")
        

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.164, rely=0.817, height=52, width=156)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="red")
        self.Button1.configure(command=admin_support.login)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font11)
        self.Button1.configure(foreground="white")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''SUBMIT''')

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.694, rely=0.817, height=52, width=156)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="red")
        self.Button2.configure(command=admin_support.back)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font=font11)
        self.Button2.configure(foreground="white")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''BACK''')


        
if __name__ == '__main__':
    vp_start_gui()





