#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    May 08, 2019 02:22:21 PM IST  platform: Windows NT

import sys
import loginpage_support
import loginpage
import admin_support
import admin
import signupp
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def adminn():
    destroy_window()
    admin.vp_start_gui()

def userr():
    destroy_window()
    loginpage.vp_start_gui()
def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import admin_user_option
    admin_user_option.vp_start_gui()





