#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Apr 12, 2019 01:50:39 PM IST  platform: Windows NT

import sys
import pymysql
import signupp
import forgot_pswd
import signupp_support
from tkinter import *
from tkinter import messagebox
import USERLIST
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global ent1
    ent1 = tk.StringVar()
    global ent2
    ent2 = tk.StringVar()


def forgett():
    destroy_window()
    forgot_pswd.vp_start_gui()

def logg():
    #try:
        db=pymysql.connect("localhost","root","1234","test",3307)
        c=db.cursor()
        sql="select * from students where email='%s' and password='%s'"%(ent1.get(),ent2.get())
        c.execute(sql)
        result=c.fetchall()
        counter=0
        i=0
        for x in result:
            counter=counter+1
            email=x[1]
        if counter>0:
            print("Login success")
            
            import face_detect32
            i=face_detect32.detect(ent1.get())
            if i>0:
                messagebox.showinfo('Login','USER VERIFIED')
                destroy_window()
                USERLIST.vp_start_gui(ent1.get())
                #db.close()
        else:
            print("INVALID USER")
            destroy_window()
            forgot_pswd.vp_start_gui()
                
            #messagebox.showinfo('Login','INVALID USER')
            #db.close()
                
    #except:
       # messagebox.showinfo('NO DATA','NO SUCH DATA AVAILABLE.....')
    
def signn():
    destroy_window()
    signupp.vp_start_gui()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import loginpage
    loginpage.vp_start_gui()





