#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Apr 12, 2019 02:09:04 PM IST  platform: Windows NT

import sys
from PIL import Image,ImageTk


try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import loginpage_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    loginpage_support.set_Tk_var()
    top = Toplevel1 (root)
    loginpage_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    loginpage_support.set_Tk_var()
    top = Toplevel1 (w)
    loginpage_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font10 = "-family {Showcard Gothic} -size 20 -weight bold "  \
            "-slant italic -underline 1 -overstrike 0"
        font11 = "-family {Segoe UI Black} -size 13 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"

        top.geometry("1350x689-5+4")
        top.title("first")
        top.configure(background="#d9d9d9")
        
        self.img=Image.open("wel.jpg")
        self.tkimage=ImageTk.PhotoImage(self.img)
        resized=self.img.resize((1500,750),Image.ANTIALIAS)
        self.image=ImageTk.PhotoImage(resized)

        self.Label=tk.Label(top)
        self.Label.place(x=1,y=1)
        self.Label.configure(background="purple")
        self.Label.configure(height=750,width=1500)
        self.Label.configure(image=self.image)


        

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.667, rely=0.044, height=41, width=174)
        self.Label1.configure(background="brown")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="white")
        self.Label1.configure(text='''LOGIN''')
        self.Label1.configure(width=174)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.617, rely=0.178, height=21, width=104)
        self.Label2.configure(background="brown")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font11)
        self.Label2.configure(foreground="white")
        self.Label2.configure(text='''Email''')
        self.Label2.configure(width=104)

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.617, rely=0.244,height=20, relwidth=0.273)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(textvariable=loginpage_support.ent1)

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.625, rely=0.356, height=21, width=94)
        self.Label3.configure(background="brown")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font11)
        self.Label3.configure(foreground="white")
        self.Label3.configure(text='''Password''')
        self.Label3.configure(width=94)

        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.617, rely=0.444,height=20, relwidth=0.273)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(textvariable=loginpage_support.ent2)
        self.Entry2.configure(show="***")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.617, rely=0.578, height=24, width=77)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="brown")
        self.Button1.configure(command=loginpage_support.logg)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font11)
        self.Button1.configure(foreground="white")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Login''')
        self.Button1.configure(width=77)

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.833, rely=0.578, height=24, width=77)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="brown")
        self.Button2.configure(command=loginpage_support.signn)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font=font11)
        self.Button2.configure(foreground="white")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Signup''')
        self.Button2.configure(width=77)

        self.Button3 = tk.Button(top)
        self.Button3.place(relx=0.633, rely=0.722, height=24, width=197)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="brown")
        self.Button3.configure(command=loginpage_support.forgett)
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font=font11)
        self.Button3.configure(foreground="white")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Forget Password''')
        self.Button3.configure(width=197)

if __name__ == '__main__':
    vp_start_gui()





