#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    May 01, 2019 12:53:02 PM IST  platform: Windows NT

import sys
from PIL import Image,ImageTk

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import resultpage_support

def vp_start_gui(*args):
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    resultpage_support.set_Tk_var()
    top = Toplevel1 (root)
    resultpage_support.init(root, top,*args)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    resultpage_support.set_Tk_var()
    top = Toplevel1 (w)
    resultpage_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font10 = "-family {Showcard Gothic} -size 15 -weight bold "  \

        font11 = "-family {Segoe UI red} -size 15 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"


                 
        top.geometry("1350x689-5+4")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.0, rely=0.0,relheight=1.500,relwidth=2.0, height=41, width=454)
        self.Canvas1.configure(selectbackground="#fca367")
        self.Canvas1.configure(selectforeground="#3617ff")
        self.Canvas1.configure(relief="raised")
        self.Canvas1.configure(width=864)
        self.Canvas1.configure(borderwidth="2")
        
        self.img = Image.open("pp.jpg")
        self.tkimage = ImageTk.PhotoImage(self.img)
        resized = self.img.resize((1500, 750),Image.ANTIALIAS)
        self.imagee = ImageTk.PhotoImage(resized)

        self.Canvas1.create_image(0,0,image=self.imagee,anchor="nw")
        

        self.Canvas1.create_text(500,50,text="Result",fill="white",font=('bold',25))
        

        
        self.Canvas1.create_text(100,150,text="Email",fill="white",font=('bold',25))

        self.Canvas1.create_text(170,370,text="Total Question",fill="white",font=('bold',25))

        
        self.Entry= tk.Entry(top)
        self.Entry.place(relx=0.299, rely=0.500,height=40, relwidth=0.223)
        self.Entry.configure(background="white")
        self.Entry.configure(disabledforeground="#a3a3a3")
        self.Entry.configure(font="TkFixedFont")
        self.Entry.configure(foreground="#000000")
        self.Entry.configure(highlightbackground="#d9d9d9")
        self.Entry.configure(highlightcolor="black")
        self.Entry.configure(insertbackground="black")
        self.Entry.configure(selectbackground="#c4c4c4")
        self.Entry.configure(selectforeground="black")
        self.Entry.configure(textvariable=resultpage_support.field)

        

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.299, rely=0.189,height=40, relwidth=0.223)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")
        self.Entry1.configure(textvariable=resultpage_support.mailfield)

        
        self.Canvas1.create_text(100,250,text="Marks",fill="white",font=('bold',25))
  

        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.299, rely=0.348,height=40, relwidth=0.223)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")
        self.Entry2.configure(textvariable=resultpage_support.marksfield)

        
        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.19, rely=0.65, height=34, width=387)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="red")
        self.Button2.configure(command=resultpage_support.Show)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="white")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Show''')
        self.Button2.configure(font=font11)


        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.550, rely=0.65, height=34, width=387)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="red")
        self.Button1.configure(command=resultpage_support.logoutt)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="white")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''LogOut''')
        self.Button1.configure(font=font11)

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

if __name__ == '__main__':
    vp_start_gui()





