#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    May 04, 2019 01:36:09 PM IST  platform: Windows NT

import sys
from PIL import Image,ImageTk
import loginpage
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import signupp_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    signupp_support.set_Tk_var()
    top = Toplevel1 (root)
    signupp_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    signupp_support.set_Tk_var()
    top = Toplevel1 (w)
    signupp_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font9 = "-family {Segoe UI} -size 11 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1350x689-5+4")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        
        self.img=Image.open("bbk.jpg")
        self.tkimage=ImageTk.PhotoImage(self.img)
        resized=self.img.resize((1500,750),Image.ANTIALIAS)
        self.image=ImageTk.PhotoImage(resized)

        self.Label=tk.Label(top)
        self.Label.place(x=1,y=1)
        self.Label.configure(background="purple")
        self.Label.configure(height=750,width=1500)
        self.Label.configure(image=self.image)


        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.02, rely=0.056,height=20, relwidth=0.319)
        self.Entry1.configure(background="cyan")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")
        self.Entry1.configure(textvariable=signupp_support.idd)
        self.Entry1.insert(0,'ID')
        self.Entry1.bind("<FocusIn>",lambda args:self.Entry1.delete('0','end'))
        

        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.674, rely=0.056,height=20, relwidth=0.293)
        self.Entry2.configure(background="cyan")
        self.Entry2.configure(disabledforeground="#528ba3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")
        self.Entry2.configure(textvariable=signupp_support.email)
        self.Entry2.insert(0,'EMAIL')
        self.Entry2.bind("<FocusIn>",lambda args:self.Entry2.delete('0','end'))
        
        
        self.Entry3 = tk.Entry(top)
        self.Entry3.place(relx=0.026, rely=0.168,height=20, relwidth=0.306)
        self.Entry3.configure(background="cyan")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")
        self.Entry3.configure(textvariable=signupp_support.username)
        self.Entry3.insert(0,'USERNAME')
        self.Entry3.bind("<FocusIn>",lambda args:self.Entry3.delete('0','end'))
        

        self.Entry4 = tk.Entry(top)
        self.Entry4.place(relx=0.674, rely=0.168,height=20, relwidth=0.293)
        self.Entry4.configure(background="cyan")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(highlightbackground="#d9d9d9")
        self.Entry4.configure(highlightcolor="black")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(selectbackground="#c4c4c4")
        self.Entry4.configure(selectforeground="black")
        self.Entry4.configure(textvariable=signupp_support.password)
        self.Entry4.configure(show="**")
        self.Entry4.insert(0,'PASSWORD')
        self.Entry4.bind("<FocusIn>",lambda args:self.Entry4.delete('0','end'))
        


        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.445, rely=0.056, height=21, width=94)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="cyan")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Gender''')

        '''self.Radiobutton1 = tk.Radiobutton(top)
        self.Radiobutton1.place(relx=0.373, rely=0.131, relheight=0.047
                , relwidth=0.115)
        self.Radiobutton1.configure(activebackground="#ececec")
        self.Radiobutton1.configure(activeforeground="white")
        self.Radiobutton1.configure(background="cyan")
        self.Radiobutton1.configure(disabledforeground="white")
        self.Radiobutton1.configure(font=font9)
        self.Radiobutton1.configure(foreground="#f7f7f7")
        self.Radiobutton1.configure(highlightbackground="#ffffff")
        self.Radiobutton1.configure(highlightcolor="white")
        self.Radiobutton1.configure(justify='left')
        self.Radiobutton1.configure(text="Male")
        self.Radiobutton1.configure(variable=signupp_support.genderr)
        #self.Radiobutton1.configure(variable=signupp_support.Malee)
        self.Radiobutton1.configure(signupp_support.genderr.set(0))
        self.Radiobutton1.configure(width=88)
        self.Radiobutton1.configure(value="Male")

        self.Radiobutton2 = tk.Radiobutton(top)
        self.Radiobutton2.place(relx=0.524, rely=0.131, relheight=0.047
                , relwidth=0.115)
        self.Radiobutton2.configure(activebackground="#ececec")
        self.Radiobutton2.configure(activeforeground="white")
        self.Radiobutton2.configure(background="cyan")
        self.Radiobutton2.configure(disabledforeground="white")
        self.Radiobutton2.configure(font=font9)
        self.Radiobutton2.configure(foreground="#f7f7f7")
        self.Radiobutton2.configure(highlightbackground="#ffffff")
        self.Radiobutton2.configure(highlightcolor="white")
        self.Radiobutton2.configure(justify='left')
        self.Radiobutton2.configure(text="Female")
        self.Radiobutton2.configure(variable=signupp_support.genderr)
        #self.Radiobutton2.configure(variable=signupp_support.Femalee)
        self.Radiobutton2.configure(signupp_support.genderr.set(0))
        self.Radiobutton2.configure(width=88)
        self.Radiobutton2.configure(value="Female")'''

        
        self.Radiobutton1 = tk.Radiobutton(top)
        self.Radiobutton1.place(relx=0.373, rely=0.131, relheight=0.047
                , relwidth=0.115)
        self.Radiobutton1.configure(activebackground="#ececec")
        self.Radiobutton1.configure(activeforeground="#000000")
        self.Radiobutton1.configure(background="cyan")
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(font=font9)
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(justify='left')
        self.Radiobutton1.configure(text='''Male''')
        self.Radiobutton1.configure(variable=signupp_support.genderr)
        self.Radiobutton1.configure(signupp_support.genderr.set(0))
        self.Radiobutton1.configure(value="Male")
        

        self.Radiobutton2 = tk.Radiobutton(top)
        self.Radiobutton2.place(relx=0.524, rely=0.131, relheight=0.047
                , relwidth=0.115)
        self.Radiobutton2.configure(activebackground="#ececec")
        self.Radiobutton2.configure(activeforeground="#000000")
        self.Radiobutton2.configure(background="cyan")
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(font=font9)
        self.Radiobutton2.configure(foreground="#000000")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="black")
        self.Radiobutton2.configure(justify='left')
        self.Radiobutton2.configure(text='''Female''')
        self.Radiobutton2.configure(variable=signupp_support.genderr)
        self.Radiobutton2.configure(signupp_support.genderr.set(0))
        self.Radiobutton2.configure(value="Female")




        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.039, rely=0.299, height=21, width=84)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="cyan")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Image''')

        self.Entry5 = tk.Entry(top)
        self.Entry5.place(relx=0.19, rely=0.28,height=30, relwidth=0.372)
        self.Entry5.configure(background="cyan")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(highlightbackground="#d9d9d9")
        self.Entry5.configure(highlightcolor="black")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(selectbackground="#c4c4c4")
        self.Entry5.configure(selectforeground="black")
        self.Entry5.configure(textvariable=signupp_support.imagefield)
        self.Entry5.insert(0,'IMAGE')
        self.Entry5.bind("<FocusIn>",lambda args:self.Entry5.delete('0','end'))
        

        
        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.654, rely=0.299, height=24, width=127)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="red")
        self.Button1.configure(command=signupp_support.selectt)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font9)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Select''')

        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.026, rely=0.392, relheight=0.438
                , relwidth=0.942)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(font=font9)
        self.Labelframe1.configure(foreground="#000000")
        self.Labelframe1.configure(text='''Security Question''')
        self.Labelframe1.configure(background="cyan")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")
        self.Labelframe1.configure(width=720)

        self.Label3 = tk.Label(self.Labelframe1)
        self.Label3.place(relx=0.014, rely=0.17, height=26, width=30
                , bordermode='ignore')
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="cyan")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font9)
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Q.1''')

        self.TCombobox1 = ttk.Combobox(self.Labelframe1)
        self.TCombobox1.place(relx=0.111, rely=0.128, relheight=0.132
                , relwidth=0.74, bordermode='ignore')
        self.value_list = ["What was your childhood nickname?" ,"In what city did you meet your spouse/significant other?","What is the name of your favorite childhood friend?","What street did you live on in third grade?","What is your oldest sibling birthday month and year? (e.g., January 1900)" ,]
        self.TCombobox1.configure(values=self.value_list)
        self.TCombobox1.configure(textvariable=signupp_support.question1)
        self.TCombobox1.configure(background="#3bbeff")
        self.TCombobox1.configure(takefocus="")

        self.Label4 = tk.Label(self.Labelframe1)
        self.Label4.place(relx=0.014, rely=0.383, height=26, width=33
                , bordermode='ignore')
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="cyan")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font=font9)
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Ans''')

        self.Entry6 = tk.Entry(self.Labelframe1)
        self.Entry6.place(relx=0.111, rely=0.362, height=30, relwidth=0.742
                , bordermode='ignore')
        self.Entry6.configure(background="cyan")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(highlightbackground="#d9d9d9")
        self.Entry6.configure(highlightcolor="black")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(selectbackground="#c4c4c4")
        self.Entry6.configure(selectforeground="black")
        self.Entry6.configure(textvariable=signupp_support.answer1)
        

        self.Label5 = tk.Label(self.Labelframe1)
        self.Label5.place(relx=0.007, rely=0.617, height=21, width=34
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="cyan")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font=font9)
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Q.2''')

        self.TCombobox2 = ttk.Combobox(self.Labelframe1)
        self.TCombobox2.place(relx=0.111, rely=0.596, relheight=0.132
                , relwidth=0.74, bordermode='ignore')
        self.value_list = ["What is the middle name of your youngest child?","What is your oldest sibling middle name?","What school did you attend for sixth grade?","What was your childhood phone number including area code?","What is your oldest cousin first and last name?",]
        self.TCombobox2.configure(values=self.value_list)
        self.TCombobox2.configure(textvariable=signupp_support.question2)
        self.TCombobox2.configure(takefocus="")

        self.Label6 = tk.Label(self.Labelframe1)
        self.Label6.place(relx=0.014, rely=0.851, height=26, width=33
                , bordermode='ignore')
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="cyan")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font=font9)
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Ans''')

        self.Entry7 = tk.Entry(self.Labelframe1)
        self.Entry7.place(relx=0.111, rely=0.809, height=30, relwidth=0.742
                , bordermode='ignore')
        self.Entry7.configure(background="cyan")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(highlightbackground="#d9d9d9")
        self.Entry7.configure(highlightcolor="black")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(selectbackground="#c4c4c4")
        self.Entry7.configure(selectforeground="black")
        self.Entry7.configure(textvariable=signupp_support.answer2)

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.052, rely=0.858, height=24, width=117)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="red")
        self.Button2.configure(command=signupp_support.submitt)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font=font9)
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Submit''')

        self.Button3 = tk.Button(top)
        self.Button3.place(relx=0.785, rely=0.868, height=24, width=117)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="red")
        self.Button3.configure(command=signupp_support.backk)
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font=font9)
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Login''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

if __name__ == '__main__':
    vp_start_gui()





