#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Apr 23, 2019 01:37:06 PM IST  platform: Windows NT
#    Apr 23, 2019 02:00:58 PM IST  platform: Windows NT
#    Apr 23, 2019 02:39:50 PM IST  platform: Windows NT
#    May 01, 2019 03:15:32 PM IST  platform: Windows NT
#    May 02, 2019 12:19:52 PM IST  platform: Windows NT

import sys
from tkinter import *
from tkinter import messagebox
import pymysql
#import admin_user_option
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global question
    question = tk.StringVar()
    question.set('Label')
    global option
    option = tk.StringVar()
    
    global option1
    option1 = tk.StringVar()
    global option2
    option2 = tk.StringVar()
    global option3
    option3 = tk.StringVar()
    global option4
    option4 = tk.StringVar()
    
    global question_number
    question_number = tk.StringVar()
    global questionumber
    questionumber = tk.StringVar()
    global counter
    counter=tk.IntVar()
    global ok
    ok=tk.StringVar()
    '''def callback(eventObject):
    #print("ello")
    db=pymysql.connect("localhost","root","1234","test",3307)
    c=db.cursor()
    sql=("select * from question where question_number='%s'"%(questionumber.get()))
    c.execute(sql)
    result=c.fetchall()
    print(result)
    counter=0
    question_number=0
    for x in result:
        counter=counter+1
        print(counter)
        question_number=x[0]
        question.set(x[1])
        option1.set(x[2])
        option2.set(x[3])
        option3.set(x[4])
        option4.set(x[5])
        correct.set(x[6])
        coursename.set(x[7])
        hours.set(x[8])
        mintues.set(x[9])
        seconds.set(x[10])
        combobox.set(x[11])
        totalquestion.set(x[12])'''

    
    global emailentry
    emailentry = tk.StringVar()
def finish():
    messagebox.showinfo('MESSAGE','Your result has been mailed')
    destroy_window()
    #admin_user_option.vp_start_gui()

def Submit():
    db=pymysql.connect("localhost","root","1234","test",3307)
    c=db.cursor()
    sql="insert into testtime(student_id,question_id,answers) values('%s','%s','%s')"%(emailentry.get(),ok.get(),option.get())
    c.execute(sql)
    db.commit()
    
def english():
    print('studentpaper_support.english')
    sys.stdout.flush()

def next():
    cn=int(ok.get())+1
    ok.set(str(cn))
    print(cn)    
    counterr(cn)
        

def previous():
    cn=int(ok.get())-1
    ok.set(str(cn))
    print(cn)
    counterr(cn)
            
def reasoning():
    print('studentpaper_support.reasoning')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    for arg in args:
        emailentry.set(arg)
    
    ok.set("0")
    db=pymysql.connect("localhost","root","1234","test",3307)
    c=db.cursor()
    sql=("select * from question where question_number='%s'"%(questionumber.get()))
    c.execute(sql)
    result=c.fetchall()
    print(result)
    
    counter=0
    question_number=0
    for x in result:
        counter=counter+1
        print(counter)
        question_number=x[0]
        question.set(x[1])
        option1.set(x[2])
        option2.set(x[3])
        option3.set(x[4])
        option4.set(x[5])
    

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import studentpaper
    studentpaper.vp_start_gui()



def counterr (count):
    
    db=pymysql.connect("localhost","root","1234","test",3307)
    c=db.cursor()
    sql=("select * from question where question_number='%s'"%(count))
    c.execute(sql)
    result=c.fetchall()
    print(result)
    counter=0
    question_number=0
    for x in result:
        counter=counter+1
        print(counter)
        question_number=x[0]
        question.set(x[1])
        option1.set(x[2])
        option2.set(x[3])
        option3.set(x[4])
        option4.set(x[5])
        

    
         

'''def optiona():
    db=pymysql.connect("localhost","root","1234","test",3307)
    c=db.cursor()
    sql="insert into testtime values('"+option1.get()+"')"
    c.execute(sql)
    db.commit()
    print(option1.get())
    
def optionb():
    db=pymysql.connect("localhost","root","1234","test",3307)
    c=db.cursor()
    sql="insert into students(optionA)values('"+option1.get()+"')"
    c.execute(sql)
    db.commit()
    print(option2.get())
    

def optionc():
    db=pymysql.connect("localhost","root","1234","test",3307)
    c=db.cursor()
    sql="insert into students(optionA)values('"+option1.get()+"')"
    c.execute(sql)
    db.commit()
    print(option3.get())
    

def optiond():
    db=pymysql.connect("localhost","root","1234","test",3307)
    c=db.cursor()
    sql="insert into students(optionA)values('"+option1.get()+"')"
    c.execute(sql)
    db.commit()
    print(option4.get())'''
    
