#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    May 15, 2019 01:42:25 PM IST  platform: Windows NT

import sys
from PIL import Image,ImageTk
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import USERLIST_support

def vp_start_gui(*args):
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    USERLIST_support.init(root, top,*args)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    USERLIST_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'red'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI} -size 11 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI red} -size 13 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"

        

        top.geometry("1350x989-5+4")
        top.title("New Toplevel")
        #top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="red")

        '''self.img = Image.open("pp.jpg")
        self.tkimage = ImageTk.PhotoImage(self.img)
        resized = self.img.resize((1474, 884),Image.ANTIALIAS)
        self.image = ImageTk.PhotoImage(resized) # Keep a reference, prevent GC'''

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.0, rely=0.0, relheight=1.426, relwidth=1.801,height=750, width=1200)
        #self.Canvas1.configure(background="#d9d9d9")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief='ridge')
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=1363)

        self.img = Image.open("pp.jpg")
        self.tkimage = ImageTk.PhotoImage(self.img)
        resized = self.img.resize((1500, 750),Image.ANTIALIAS)
        self.image = ImageTk.PhotoImage(resized) # Keep a reference, prevent GC
        
        self.Canvas1.create_image(0,0,image=self.image,anchor="nw")
        self.Canvas1.create_text(680,200, text="ONLINE EXAMINATION",fill="red",font=('bold',60))
        self.Canvas1.create_text(655,380, text="SYSTEM",fill="red",font=('bold',60))
        
        '''self.Label = tk.Label(top)
        self.Label(top,image =self.image,height=750,width=1500,bg="purple").place(x=1,y=1)'''
        
        '''self.Label0=tk.Label(top)
        self.Label0.place(x=1,y=1)
        self.Label0.configure(background="purple")
        self.Label0.configure(height=884,width=1474)
        self.Label0.configure(image =self.image)'''

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.481, rely=0.74, height=34, width=157)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="red")
        self.Button1.configure(command=USERLIST_support.RESULT)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="white")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(font=font11)
        self.Button1.configure(highlightcolor="red")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''RESULT''')
        self.Button1.configure(width=187)

        '''self.Button4 = tk.Button(top)
        self.Button4.place(relx=0.53, rely=0.455, height=34, width=177)
        self.Button4.configure(activebackground="#ececec")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="red")
        self.Button4.configure(command=USERLIST_support.login)
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="white")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(font=font11)
        self.Button4.configure(highlightcolor="red")
        self.Button4.configure(pady="0")
        self.Button4.configure(text="LOGIN")
        self.Button4.configure(width=177)'''

        '''self.Button5 = tk.Button(top)
        self.Button5.place(relx=0.218, rely=0.19, height=34, width=197)
        self.Button5.configure(activebackground="#ececec")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="red")
        self.Button5.configure(command=USERLIST_support.FORGETPAGE)
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(font=font11)
        self.Button5.configure(foreground="white")
        self.Button5.configure(highlightbackground="#d9d9d9") self.Button1.place(relx=0.384, rely=0.323, height=34, width=197)
        self.Button5.configure(highlightcolor="red")
        self.Button5.configure(pady="0")
        self.Button5.configure(text="FORGET PASSWORD")
        self.Button5.configure(width=197)'''

        '''self.Button7 = tk.Button(top)
        self.Button7.place(relx=0.328, rely=-0.271, height=34, width=267)
        self.Button7.configure(activebackground="#ececec")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background="red")
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(font=font11)
        self.Button7.configure(foreground="white")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="red")
        self.Button7.configure(pady="0")
        self.Button7.configure(text="EXAM")'''

        '''self.Button8 = tk.Button(top)
        self.Button8.place(relx=0.665, rely=0.607, height=34, width=197)
        self.Button8.configure(activebackground="#ececec")
        self.Button8.configure(activeforeground="#000000")
        self.Button8.configure(background="red")
        self.Button8.configure(command=USERLIST_support.SIGNUPPAGE)
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(font=font11)
        self.Button8.configure(foreground="white")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="red")
        self.Button8.configure(pady="0")
        self.Button8.configure(text="SIGNUP")
        self.Button8.configure(width=197)'''

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.181, rely=0.74, height=34, width=157)
        
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="red")
        self.Button2.configure(command=USERLIST_support.questionn)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="white")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(font=font11)
        self.Button2.configure(highlightcolor="red")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''EXAM''')
        self.Button2.configure(width=197)

        self.Button3 = tk.Button(top)
        self.Button3.place(relx=0.81, rely=0.74, height=34, width=157)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="red")
        self.Button3.configure(font=font11)
        self.Button3.configure(command=USERLIST_support.BACKK)
        self.Button3.configure(disabledforeground="#a3a3a3")
        
        self.Button3.configure(foreground="white")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="red")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''BACK''')
        self.Button3.configure(width=157)

if __name__ == '__main__':
    vp_start_gui()





