#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    May 06, 2019 02:33:18 PM IST  platform: Windows NT
#    May 06, 2019 02:36:59 PM IST  platform: Windows NT
#    May 15, 2019 01:42:30 PM IST  platform: Windows NT

import sys
import studentpaper
import signupp
import signupp_support
import forget_password
import forget_password_support
import loginpage
import loginpage_support
import resultpage
import resultpage_support
import admin_user_option
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def BACKK():
    destroy_window()
    admin_user_option.vp_start_gui()

def questionn():
    destroy_window()
    studentpaper.vp_start_gui(argg.get())

'''def FORGETPAGE():
    destroy_window()
    forget_password.vp_start_gui()

def login():
    destroy_window()
    loginpage.vp_start_gui()'''

def RESULT():
    destroy_window()
    resultpage.vp_start_gui(argg.get())

'''def SIGNUPPAGE():
    destroy_window()
    signupp.vp_start_gui()'''

def init(top, gui, *args, **kwargs):
    global argg
    argg = tk.StringVar()
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    for arg in args:
        argg.set(arg)


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import USERLIST
    USERLIST.vp_start_gui()




